FAMEBooks/Controllers/BookController.cs
using FAMEBooks.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FAMEBooks.ViewModels;
using FAMEBooks.Repositories;
using Microsoft.AspNetCore.Authorization;
using FAMEBooks.ViewModels.Book;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;

namespace FAMEBooks.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BookController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly UserManager<AppUser> userManager;

        public BookController(IBookRepository bookRepository,
                              ICategoryRepository categoryRepository,
                              UserManager<AppUser> userManager)
        {
            this.bookRepository = bookRepository;
            this.categoryRepository = categoryRepository;
            this.userManager = userManager;
        }

        public ViewResult Index()
        {
            return View();
        }

        public async Task<List<DisplayViewModel>> Books()
        {
            var result = await bookRepository.GetBooks();
            return result;
        }


        [AllowAnonymous]
        public async Task<IActionResult> Create()
        {
            ViewBag.Categories = new SelectList(await categoryRepository.Categories(), "CategoryId", "CategoryName");
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create(CreateViewModel model)
        {
            model.BookId = Guid.NewGuid();
            model.CreatedByUserId = userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                try
                {
                    await bookRepository.AddAsync(model);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View(model);
        }

        // GET: CategoryController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var book = await bookRepository.GetBook(id);
            ViewBag.Categories = new SelectList(await categoryRepository.Categories(), "CategoryId", "CategoryName", new { id = book.CategoryId });
            var model = new EditViewModel
            {
                Author = book.Author,
                //AvailableBookCount = book.BookCount,
                BookCount = book.BookCount,
                BookId = book.BookId,
                CategoryId = book.CategoryId,
                DatePublished = book.DatePublished,
                ISBN = book.ISBN,
                Pages = book.Pages,
                Publisher = book.Publisher,
                //Status = Status.Available,
                Title = book.Title,
            };
            return View(model);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditViewModel model)
        {
            model.UpdatedByUserId = userManager.GetUserId(User);
            if (ModelState.IsValid)
            {
                var result = await bookRepository.UpdateAsync(model.BookId, model);
                if (result == null)
                {
                    ModelState.AddModelError("", "Error while updating item.");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: CategoryController/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            var book = await bookRepository.GetBook(id);

            var bookToDelete = new DisplayViewModel
            {
                Author = book.Author,
                BookCount = book.BookCount,
                CategoryId = book.CategoryId,
                DatePublished = book.DatePublished,
                ISBN = book.ISBN,
                Pages = book.Pages,
                Publisher = book.Publisher,
                Title = book.Title,
                BookId = book.BookId,
                DateCreated = book.DateCreated,
                Category = book.Category.CategoryName,
                CreatedBy = book.BookCreatedBy.FirstName + " " + book.BookCreatedBy.LastName,
                UpdatedBy = book.BookUpdatedBy != null ? book.BookUpdatedBy.FirstName + " " + book.BookUpdatedBy.LastName : "No Updates",
            };
            return View(bookToDelete);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DisplayViewModel model)
        {
            try
            {
                var result = await bookRepository.DeleteAsync(model.BookId);
                if (result != null)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", "Error deleting item.");
                return View(model);
            }
            catch
            {
                return View();
            }
        }
    }
}

FAMEBooks/Controllers/CategoryController.cs
using FAMEBooks.Models;
using FAMEBooks.Repositories;
using FAMEBooks.ViewModels.Category;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FAMEBooks.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }

        // GET: CategoryController
        public IActionResult Index()
        {
            // var result = await categoryRepository.GetCategories();
            return View();
        }

        public async Task<JsonResult> Categories()
        {
            return Json(await categoryRepository.GetCategories());
        }

        // GET: CategoryController/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create(ViewModels.Category.CreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await categoryRepository.AddAsync(model);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            return View(model);
        }

        // GET: CategoryController/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await categoryRepository.GetCategory(id);

            var model = new EditViewModel
            {
                CategoryName = result.CategoryName,
                CategoryId = result.CategoryId
            };
            return View(model);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await categoryRepository.UpdateAsync(model);
                if (result == null)
                {
                    ModelState.AddModelError("", "Error while updating item.");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: CategoryController/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await categoryRepository.GetCategory(id);
            return View(result);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Models.Category model)
        {
            try
            {
                var result = await categoryRepository.DeleteAsync(model.CategoryId);
                if (result != null)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", "Error deleting item.");
                return View(model);
            }
            catch
            {
                return View();
            }
        }

    }
}

FAMEBooks/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

FAMEBooks/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/datatables/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <a class="navbar-brand" href="#">FAME Books</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="index" asp-controller="Home">Home<span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" asp-action="index" asp-controller="Book">Books<span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" asp-action="index" asp-controller="Category">Categories<span class="sr-only">(current)</span></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administration
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-action="listroles" asp-controller="administration">Roles</a>
                                    <a class="dropdown-item" asp-action="listusers" asp-controller="administration">Users</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    </ul>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <div class="form-inline my-2 my-lg-0">
                            <div class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <form method="post" asp-action="logout" asp-controller="account">
                                        <button type="submit" class="dropdown-item">Logout</button>
                                    </form>
                                    <a class="dropdown-item" asp-action="changepassword" asp-controller="account">Change  Password</a>
                                    <a class="dropdown-item" asp-action="addpassword" asp-controller="account">Add  Password</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">My Profile</a>
                                </div>
                            </div>
                        </div>
                    }
                    else
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="register">
                                    Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="login">
                                    Login
                                </a>
                            </li>
                        </ul>
                    }
                </div>
            </nav>
        </header>

        <main>
            @RenderBody()
        </main>

        <footer></footer>
    </div>

    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/popper.js/umd/popper.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/datatables/datatables.min.js"></script>

    @RenderSection("Styles", false)
    @RenderSection("Scripts", false)
</body>
</html>